// <auto-generated />
namespace Rheal_Assignment_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StudentCourseIsCompleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentCourseIsCompleted));
        
        string IMigrationMetadata.Id
        {
            get { return "202011282108416_StudentCourseIsCompleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
